base_url = 'https://shuiyuan.sjtu.edu.cn'
search_url = f'{base_url}/search.json?'
user_actions_url = f'{base_url}/user_actions.json?'
user_badges_url = f'{base_url}/user-badges'
post_url = f'{base_url}/posts'
not_found_error = '找不到请求的 URL 或资源。'
topic_closed_blurb = '此话题已在最后回复的 90 天后被自动关闭。不再允许新回复。'
too_many_operations_warning = '您执行此操作的次数过多，请稍后再试。'